require("plugins.base.nvim-tree")
require("plugins.base.whichkey")
require("plugins.base.bookmark")
require("plugins.base.telescope")
require("plugins.base.cmp")
require("plugins.base.treesitter")
require("plugins.base.gitsigns")
